apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccc
  template:
    metadata:
      labels:
        app: ccc
    spec:
      containers:
      - image: okteto.dev/ccc:latest
        name: ccc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2cc15b63-be56-427f-9e4a-1f7976dc00f5"
        - name: Vless_Path
          value: "/vlc411"
        - name: Vmess_UUID
          value: "2cc15b63-be56-427f-9e4a-1f7976dc00f5"
        - name: Vmess_Path
          value: "/vmc411"
        - name: Share_Path
          value: "/v2link"
